[project]
name = "colonoscopy-polopy-detection-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "opencv-python>=5.0.0.93",
    "ultralytics>=8.4.146",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
